### ISSUE TITLE
crazy 

### ISSUE THREAD

**Issue by DaDevGuy** [GabBiswajit/LunarGames-#3]
where u got this from?  i thought the website went off after i didnt pay for domain

**Comment by GabBiswajit** [comment]
Idk, I Just Get It Because I Fix The Lunar Gamers Backup And Updete To Last Version!

**Comment by DaDevGuy** [comment]
you stole that off me or something im lunargames owner ;-;

**Comment by GabBiswajit** [comment]
Maybe you forgot I buy LunerBackup From You Before It Leak.

@DaDevGuy This Website I Create Just For Fun I Just Get This On My Old Folder So I think To Try It, I Don't Going To Release It.

Because it's Waste Of Time.

**Comment by DaDevGuy** [comment]
alright fair enough you might aswell close this issue now
